### ISSUE TITLE
Debug feature: Account generator

### ISSUE THREAD

**Issue by skomski** [famedly/ldap-sync#29]
For testing the mandatory room feature on the staging server it would be good to have the possibility to create quickly a lot of accounts with random data. We could hide it behind a feature flag to avoid public visibility.
Or should we put this feature into a separate debug tool?

**Comment by tlater-famedly** [comment]
Hm, we could have a set of utility scripts/tools somewhere. I don't think this is the right place for it, since this tool focuses very heavily on syncing ldap to zitadel - unless we want to generate random ldap users first, ldap-sync probably shouldn't grow functionality to generate random users just because we have a need for testing elsewhere.

**Comment by skomski** [comment]
Yes, completely, but one downside to having a separate tool is that we have to keep it up to date with the sync tool how we create Zitadel accounts. I will think of a good way to implement a debugging tool after my tests.

**Comment by tlater-famedly** [comment]
That's why `zitadel-rust-client` exists, to be fair

**Comment by nikzen** [comment]
I don't see such a feature here
